# Generated by Django 3.1 on 2022-01-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='announce',
            name='title_city_source_unique_constraint',
        ),
        migrations.AddConstraint(
            model_name='announce',
            constraint=models.UniqueConstraint(fields=('title', 'city', 'source', 'price'), name='title_city_source_price_unique_constraint'),
        ),
    ]
